[libraries]
bre.files = [
    '../lib/common/hdl/pkg/*.vhd',
    '../lib/common/hdl/src/vhdl/*.vhd'
]

UNISIM.files = [
    '/home/danderson/Xilinx/Vivado/2022.1/data/vhdl/src/unisims/unisim_VCOMP.vhd'
]
UNISIM.is_third_party = true
